"""The 1,000 most common English words, for the typing trainer (src/lib/train/words.ts).

The 10-word speed test draws from all of them; each level draws from the ones
that can be typed with the keys learned so far (src/lib/train/levels.ts), so
every word on every test is one of the thousand.

    pip install wordfreq english_words
    python scripts/train/build-words.py

Words come from wordfreq's English list in order of frequency, kept only when
the web2/gcide dictionary has them in lower case (that drops names: john,
paris, monday, and lone letters) and they are not on BLOCK below.
Contractions are kept, except the ones on a lower-case i.
"""
import os
from wordfreq import top_n_list
from english_words import get_english_words_set

OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'src', 'lib', 'train', 'words.ts')
COUNT = 1000

# Two-letter words are kept only when they are words people type.
TWO = set('as at an he it is in on so no do to us of or if go up by my we me be am oh'.split())

# Words a keyboard shop's practice text should not hand anyone: profanity,
# sex, slurs, violence and drugs, plus fragments and names the dictionary
# lets through.
BLOCK = set('''
fuck fucking fucked fucker fucks shit shitty shits bullshit damn damned hell ass asses asshole
bitch bitches bastard dick dicks cock cocks pussy cunt cum tit tits titty boob boobs slut sluts
whore whores piss pissed crap crappy wank horny sex sexy sexual sexually porn porno nude nudes
naked anal oral rape raped rapist rapes kill killed killing kills killer killers murder murders
murdered dead death deaths die died dies dying suicide gun guns shot shoot shooting shooter bomb
bombs bombing war wars terror terrorist terrorism attack attacks attacked abuse abused victim
victims blood bloody corpse drug drugs cocaine heroin weed meth stoned drunk nazi nazis hitler
slave slaves slavery gay gays lesbian negro nigger nigga fag fags faggot retard retarded spic
kike chink homo queer tranny jesus christ god gods satan devil trump hooker strip stripper
non june york ii iii iv vi vii viii xi xii etc san anti gonna wanna gotta canada german
'''.split())

# 's only where it means "is" or "us"; possessives (world's) read oddly alone.
S_CONTRACTIONS = set("it's that's he's she's there's what's here's who's let's where's".split())


def ok(w, lower):
    if not w.isascii() or w in BLOCK:
        return False
    if "'" in w:
        if w.count("'") != 1 or w.startswith("i'") or w == "ain't":
            return False
        base, tail = w.split("'")
        if not base.isalpha():
            return False
        return w in S_CONTRACTIONS if tail == 's' else tail in ('t', 're', 've', 'll', 'd')
    if not w.isalpha() or len(w) > 12:
        return False
    if len(w) == 1:
        return w == 'a'
    if len(w) == 2 and w not in TWO:
        return False
    return w in lower


def main():
    lower = get_english_words_set(['web2', 'gcide'], lower=False, alpha=True)
    words = [w for w in top_n_list('en', 5000) if ok(w, lower)][:COUNT]
    assert len(words) == COUNT, len(words)

    lines = [' '.join(words[i:i + 20]) for i in range(0, COUNT, 20)]
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write("// Generated by scripts/train/build-words.py from wordfreq's English list: do not edit.\n")
        f.write('// The 1,000 most common English words, most common first.\n\n')
        f.write('export const TOP_WORDS: string[] = [\n')
        for line in lines:
            f.write('  "%s",\n' % line)
        f.write(']\n  .join(" ")\n  .split(" ")\n')
    print('%d words, last: %s' % (len(words), ' '.join(words[-10:])))
    print('wrote', os.path.normpath(OUT))


if __name__ == '__main__':
    main()
